// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rzonca_Babik_FixCar4Us.Data;

#nullable disable

namespace Rzonca_Babik_FixCar4Us.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToolId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToolId2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToolId3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkstationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DiscountRatePercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.EfmigrationsLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("__EFMigrationsLock", (string)null);
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.OrderPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PriceAtTheTime")
                        .HasColumnType("REAL");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepairOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("OrderParts");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.OrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FinalPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("LoggedHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("RepairOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RepairOrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderServices");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PurchasePrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("SalePrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.RepairHistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepairOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotData")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RepairHistoryLogs");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.RepairOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdditionalFee")
                        .HasColumnType("REAL");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DifficultyDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IsFleet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportedIssues")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("RepairOrders");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BaseHourlyRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredSpeciality")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.TechnicalInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("TechnicalInspections");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Workstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxLiftWeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Appointment", b =>
                {
                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Workstation", "Workstation")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkstationId");

                    b.Navigation("Employee");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.OrderPart", b =>
                {
                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Part", "Part")
                        .WithMany("OrderParts")
                        .HasForeignKey("PartId");

                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.RepairOrder", "RepairOrder")
                        .WithMany("OrderParts")
                        .HasForeignKey("RepairOrderId");

                    b.Navigation("Part");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.OrderService", b =>
                {
                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Customer", "Customer")
                        .WithMany("OrderServices")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.RepairOrder", "RepairOrder")
                        .WithMany("OrderServices")
                        .HasForeignKey("RepairOrderId");

                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Service", "Service")
                        .WithMany("OrderServices")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Customer");

                    b.Navigation("RepairOrder");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.RepairOrder", b =>
                {
                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Vehicle", "Vehicle")
                        .WithMany("RepairOrders")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.TechnicalInspection", b =>
                {
                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Vehicle", "Vehicle")
                        .WithMany("TechnicalInspections")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Vehicle", b =>
                {
                    b.HasOne("Rzonca_Babik_FixCar4Us.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Customer", b =>
                {
                    b.Navigation("OrderServices");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Employee", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Part", b =>
                {
                    b.Navigation("OrderParts");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.RepairOrder", b =>
                {
                    b.Navigation("OrderParts");

                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Service", b =>
                {
                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Vehicle", b =>
                {
                    b.Navigation("RepairOrders");

                    b.Navigation("TechnicalInspections");
                });

            modelBuilder.Entity("Rzonca_Babik_FixCar4Us.Models.Workstation", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
